name: 4-1-Create Base EC2-Terraform Apply
on: workflow_dispatch
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_DEV_CLI_ADMIN_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_DEV_CLI_ADMIN_SECRET }}
  AWS_SSH_PUBLIC_KEY: ${{ secrets.AWS_DEV_CLI_ADMIN_SSH_PUBLIC_KEY }}  

jobs:
  terraform_apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    defaults:
      run: 
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up SSH agent
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.AWS_DEV_CLI_ADMIN_SSH_PRIVATE_KEY }}
    - name: Terraform Apply
      run: |
        cd ./4-create-base-ec2
        terraform init        
        terraform apply -auto-approve


# TF_VAR_AWS_SSH_PRIVATE_KEY=${{ secrets.AWS_DEV_CLI_ADMIN_SSH_PRIVATE_KEY }} terraform apply -auto-approve        